// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPiAnAEQsVPU_IjMu02tHokz0lpQUZGes',
    appId: '1:70611380676:web:6a159444f0f7be5f829c91',
    messagingSenderId: '70611380676',
    projectId: 'mobile-lab-flutter-fireb-b6835',
    authDomain: 'mobile-lab-flutter-fireb-b6835.firebaseapp.com',
    storageBucket: 'mobile-lab-flutter-fireb-b6835.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlH9JvU-0Zxjqz0TfIxop8lrBh_0tTsY',
    appId: '1:70611380676:android:0ed35a57ac038042829c91',
    messagingSenderId: '70611380676',
    projectId: 'mobile-lab-flutter-fireb-b6835',
    storageBucket: 'mobile-lab-flutter-fireb-b6835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyl1HufGKhCqwRpGRE--F1tdH_Nsg0sMc',
    appId: '1:70611380676:ios:55a1fa8588ad592d829c91',
    messagingSenderId: '70611380676',
    projectId: 'mobile-lab-flutter-fireb-b6835',
    storageBucket: 'mobile-lab-flutter-fireb-b6835.appspot.com',
    iosClientId: '70611380676-ajo5irknlgsisnfpnph4cdglkur5mpe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyl1HufGKhCqwRpGRE--F1tdH_Nsg0sMc',
    appId: '1:70611380676:ios:55a1fa8588ad592d829c91',
    messagingSenderId: '70611380676',
    projectId: 'mobile-lab-flutter-fireb-b6835',
    storageBucket: 'mobile-lab-flutter-fireb-b6835.appspot.com',
    iosClientId: '70611380676-ajo5irknlgsisnfpnph4cdglkur5mpe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );
}
